### ISSUE TITLE
Allow to skip artifacts signing during build

### ISSUE THREAD

**Issue by khed** [figo-connect/java-figo#19]
The travis builds fail due to missing environment configuration required to sign the artifacts.

Since signing is not necessary for builds I'd recommend to make the artifact signing optional.

E.g.:

``` xml
<properties>
...
    <skip.artifacts.signing>true</skip.artifacts.signing>
</properties>
...
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <configuration>
        <skip>${skip.artifacts.signing}</skip>
    </configuration>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

if you want to sign the artifacts for release simply run the build with the System Property `-Dskip.artifacts.signing=false`.

**Comment by khed** [comment]
FYI I did the change in the referenced commit but it is based on my PR #18 - would be great to have that applied as well :)

**Comment by asbachb** [comment]
I don't think that's really useful. With your fix you provide the same functionality which is also provided by the plugin itself:

see http://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html#skip

I'll suggest remove the configuration part entirely:

https://github.com/figo-connect/java-figo/pull/24/commits/57cde14c5b0935d03e0457f307a0c04300efea93

**Comment by berend** [comment]
Signing works fine now. Closing this.
