### ISSUE TITLE
Support submission of payments in non-interactive mode

### ISSUE THREAD

**Issue by khed** [figo-connect/java-figo#21]
Currently `FigoSession` returns the URL to be opened in a web browser when `submitPayment`is used to submit a `Payment`.

For non-browserclients it is necessary to return the  `TaskTokenResponse`instead of the url to be able to monitor the task state.

**Comment by berend** [comment]
Thanks for your question. You are right, wrapping the task polling during paments is missing. We are currently evaluating providing this in the SDK. The problem or concern is that the PSD2 is probably going to change how partner use and how we allowed to provide this feature. Meaning: All our partners either need a PSD2 license or need to use our web frontend to enter TANs during payment submission.

If you have questions regarding your workflow in the scope of PSD2, feel free to contact us directly at support@figo.io

Any changes will be announced via partner mailing and in SDK release notes.
