### ISSUE TITLE
Preserve HTTP response code when throwing FigoException

### ISSUE THREAD

**Issue by khed** [figo-connect/java-figo#22]
`FigoException` should contain the HTTP response code - if any - to enable client code to distinguish between different error situations.

**Comment by danielnaber** [comment]
Also, it should contain the description (not just the message) in a `toString()` method.

**Comment by berend** [comment]
The error code should be present in the current SDK version, see [here](https://github.com/figo-connect/java-figo/blob/master/src/main/java/me/figo/FigoException.java#L78-L93).

Feedback on that is welcome!
