### ISSUE TITLE
misleading javadoc for FigoConnection.credentialLogin()

### ISSUE THREAD

**Issue by danielnaber** [figo-connect/java-figo#23]
`FigoConnection.credentialLogin()` is supposed to take a `username` as a parameter. For me, it only works with an email address. If the username is always an email address, this should be clearly documented.

**Comment by steinke** [comment]
Hi
yes the username is always an email address. We will try to improve the documentation so this becomes more obvious in case you are not creating the user yourself

**Comment by berend** [comment]
I updated the docs, this will land in the next release (I didn't consider this worthy for a release of its own)
