### ISSUE TITLE
Changed fingerprint

### ISSUE THREAD

**Issue by w31d1-yoleco** [figo-connect/java-figo#25]
Hello, the changed fingerprint for SHA1 certificate is not listed in FigoTrustManager. API is currently not working

**Comment by achimsen** [comment]
Hi,

it is:

https://github.com/figo-connect/java-figo/blob/master/src/main/java/me/figo/internal/FigoTrustManager.java#L41

**Comment by w31d1-yoleco** [comment]
Thanks for your support. Sorry, we were using the 1.3.0 Version. But it seems the version number for the maven dependency named here is: 1.4**.0** not completely correct. According to https://mvnrepository.com/artifact/me.figo/sdk it is 1.4

**Comment by berend** [comment]
Fingerprint should be up to date, closing this.
