### ISSUE TITLE
Fingerprint of the Sandbox isn't listed

### ISSUE THREAD

**Issue by d0x** [figo-connect/java-figo#26]
Hi, the fingerprint of the Sandbox Endpoint isn't listed.

Please mention in the [Sandbox Documentation](http://sandbox.figo.io/#sandbox) that useres need to call

```
FigoTrustManager.addTrustedFingerprint("137AE242722970D5793F94192F1694083AAAED7B");
```

Or add the Key to the FigoTrustManager.

Thanks a lot.

Best Regards,
Christian.

**Comment by berend** [comment]
As of now our sandbox is out of date and will be replaced by a newer version. During that we add the sandbox fingerprint to the SDKs.

**Comment by berend** [comment]
closing this. If there are changes regarding the sandbox we will announce this in partner mailings and SDK release notes.
