### ISSUE TITLE
Why is 'getTaskState(String tokenId,String pin)' deprecated

### ISSUE THREAD

**Issue by w31d1-yoleco** [figo-connect/java-figo#27]
Hello. I recognized that the **'getTaskState(String tokenId,String pin)** method is declared deprecated. The method seems essential to send the pin when a synchronisation-task was started and the pin is not saved with the bank contact. Is there a reason why it was declared deprecated and do you plan to 'replace' it with another version, that has the pin as a parameter?

Thanks in advance.

**Comment by berend** [comment]
It was deprecated in favor of `submitResponseToTask(String tokenId, String response, TaskResponseType type)`. Depending on the type you can also use that to send a pin. [See](https://github.com/figo-connect/java-figo/blob/master/src/main/java/me/figo/FigoSession.java#L1303-L1336) here in the code. That function misses proper doc strings though...
