### ISSUE TITLE
commons-codec 1.10 library dependency in java-figo sdk

### ISSUE THREAD

**Issue by patrickff79** [figo-connect/java-figo#28]
When using sdk-1.3.10.jar in an android application the programm throws a NoSuchMethodError see
http://stackoverflow.com/questions/2047706/apache-commons-codec-with-android-could-not-find-method

**Comment by makst** [comment]
@javaes take look at the this line https://github.com/figo-connect/java-figo/blob/36d511e19bbfb0600fdfeb842b15a7653cae8333/src/main/java/me/figo/internal/FigoTrustManager.java#L85

Possible solution might be https://github.com/mpetazzoni/ttorrent/issues/144

**Comment by berend** [comment]
This was solved by adding guava and using the hex encode from there.
