### ISSUE TITLE
Support of encryption 

### ISSUE THREAD

**Issue by w31d1-yoleco** [figo-connect/java-figo#29]
Hello, when will 'java-figo' support encrypted credentials? Like: 

{
  "bank_code": "90090042",
  "country": "de",
  "credentials":
  **{
     "type": "encrypted",
     "value": "eyJhbGciOiJSU0ExXzUiLCJlbmMi..."
   },**
  "sync_tasks": [
    "standingOrders"
  ]
}

**Comment by Exordian** [comment]
why should that be needed? everything goes through https anyway

**Comment by w31d1-yoleco** [comment]
My question was concerning **JWE** encryption. So that the credentials are encrypted on client-side. That way they never are visible to the service that forwards them to figo in cleartext.

**Comment by berend** [comment]
adding JWE to `SetupAccountRequest` is on our roadmap. I will keep this open until it arrives.

**Comment by berend** [comment]
Also, after thinking about this a bit more in details. When talking this scenario:

(app)  <->  (partner-server)  <->  (figo-api)

JWE should be used to hide credentials from the partner server. The SDK is probably not in use in the app, but on the partner-server. So my proposal would be to have a separate lib to handle this and not build this into the SDK.

@w31d1-yoleco can you confirm this scenario, the use case and would a separate lib work for you?

**Comment by berend** [comment]
and I totally confirm that handling the cipher suite selection and public key handling should be part of a lib that our partner do not have to worry about.

**Comment by berend** [comment]
no feedback so far, I am available here or via bk at figo dot io. No plan so far to include encryption in the SDK. Also as starters, have a look at https://github.com/figo-connect/figo_jwe_example, this is a full example how to send encrypted credentials to figo's API.

closing this
