### ISSUE TITLE
using float for amount values

### ISSUE THREAD

**Issue by halber** [figo-connect/java-figo#3]
For example:
```Java
public class AccountBalance {
    /**
     * Account balance or None if the balance is not yet known
     */
    @Expose(serialize = false)
    private float balance;
```

Try values like 131072.01 or 16777217.

FYI:
https://blogs.oracle.com/CoreJavaTechTips/entry/the_need_for_bigdecimal
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by achimsen** [comment]
ouch, thanks for your hint, we have changed all floats to BigDecimals
