### ISSUE TITLE
Deploy current version to maven

### ISSUE THREAD

**Issue by machajdik** [figo-connect/java-figo#8]
Hi,
would be great if someone could deploy the current version (1.2.4?) to maven. The current version on maven (1.2.1) has some (quite nasty :-)) bugs (e.g., not returning "expires_in" when authenticating).

thanks!
Manuel

**Comment by machajdik** [comment]
Thanks!

**Comment by machajdik** [comment]
Someone cheered too soon, 1.2.5 seems not to be available in maven.

**Comment by achimsen** [comment]
Hi,

we had some trouble in signing the 1.2.5 artifact, sorry. But we have released it now so it should only be a matter of time when it appears in maven.

thanks
Joachim

**Comment by machajdik** [comment]
Great! thanks for the effort :+1:
